### ISSUE TITLE
Proposal: add more flexible dnsMode to (Cluster)Domain resources

### ISSUE THREAD

**Issue by cbarbian-sap** [SAP/cap-operator#216]
Currently, in `Domain` and `ClusterDomain` the `spec.dnsMode` can be passed as `None`, `Wildcard` or `Subdomain`.

We propose a fourth value, e.g. `Custom`, which would allow to tweak the created DNS records in a more flexible way. If selected, a new list attribute `spec.dnsPatterns` can be used to define the records. Note that it should not be allowed to specify this attribute if `dnsMode` is not `Custom`. Such as 

```yaml
spec:
  dnsMode: Custom
  dnsPatterns:
  - name: "host.$domain"
     target: "$dnsTarget"
  - name: "*.$domain"
     target: "other.host"
  - name: "$tenantSubdomain.$domain"
    target: "$dnsTarget"
```

The following variables would be allowed in the patterns:
- `$domain`: the value of `spec.domain`
- `$dnsTarget`: the effective ingress target, as specified by `spec.dnsTarget`, or derived from `spec.istioIngressSelector`
- `$tenantSubdomain`: the subdomain of a `CAPTenant`

And records are maintained with the following logic:
- by default, each pattern results in one DNS record
- if `name` contains `$tenantSubdomain`, then a record will be maintained for every tenant
- the variable `$tenantSubdomain` must only occur in `target` if it also occurs in `name`.

Note that the other `dnsMode` values are special cases of `Custom`:
- `None` is equivalent to an empty `dnsPattern` list
- `Wildcard` is equivalent to

  ```yaml
  dnsPatterns:
  - name: "*.$domain"
    target: "$dnsTarget"
  ```
- `Subdomain` is equivalent to

  ```yaml
  dnsPatterns:
  - name: "$tenantSubdomain.$domain"
    target: "$dnsTarget"
  ```

A further improvement could be to allow Go templates (maybe with some basic functions such as sprig) instead of the primitive variable substitution proposed above.
