### ISSUE TITLE
CAPTenant versionUpgradeStrategy "none" -> "never"

### ISSUE THREAD

**Issue by sTb1337** [SAP/cap-operator#53]
We are running CAP Operator version v0.0.1.

Try to create CAPTenant but fails with: "Unsupported value: "none": supported values: "always", "never""

```yaml
apiVersion: sme.sap.com/v1alpha1
kind: CAPTenant
metadata:
  labels:
  name: name-57afeee7-8f73....
  namespace: aas-digital-twin
spec:
  capApplicationInstance: ...
  subDomain: ....
  tenantId: ....
  version: '1'
  versionUpgradeStrategy: none
```

Documentation at https://sap.github.io/cap-operator/docs/usage/resources/captenant/ says:
`The versionUpgradeStrategy is by default always, but can be set to none in exceptional cases to prevent an automatic upgrade of the tenant.`

What is correct?
